# Generated by Django 4.2.11 on 2024-04-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=255)),
                ('is_editor', models.BooleanField(default=False)),
            ],
        ),
    ]
